# Generated by Django 2.1.5 on 2022-03-18 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='endDate',
            field=models.DateField(default=datetime.date(2022, 3, 18)),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'course', 'assignment')},
        ),
    ]
