# Generated by Django 2.1.5 on 2022-03-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0002_auto_20220315_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='geoUri',
        ),
    ]
