# Generated by Django 2.1.5 on 2022-02-20 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ltc_main', '0002_course_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('result', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Professor', 'Professor'), ('Teaching assistant', 'Teaching assistant'), ('Administrator', 'Administrator')], default='Professor', max_length=64)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='professor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='A', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Monday', max_length=9),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time',
            field=models.FloatField(default=9),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltc_main.Course'),
        ),
        migrations.AddField(
            model_name='grade',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltc_main.Staff'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltc_main.Student'),
        ),
        migrations.AddField(
            model_name='event',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltc_main.Course'),
        ),
        migrations.AddField(
            model_name='event',
            name='student',
            field=models.ManyToManyField(blank=True, to='ltc_main.Student'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_slot',
            field=models.ManyToManyField(blank=True, to='ltc_main.TimeSlot'),
        ),
        migrations.AddField(
            model_name='degree',
            name='course',
            field=models.ManyToManyField(to='ltc_main.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ltc_main.Staff'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('course', 'name')},
        ),
    ]
