# Generated by Django 2.1.5 on 2022-03-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0003_remove_event_geouri'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='geoUri',
            field=models.CharField(default='geo:55.8726,-4.2896?z=16', max_length=128),
        ),
    ]
