# Generated by Django 2.1.5 on 2022-03-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0004_event_geouri'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ednDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
