# Generated by Django 2.1.5 on 2022-02-20 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0004_auto_20220220_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ltc_main.Course'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ltc_main.Event'),
        ),
    ]
