# Generated by Django 2.1.5 on 2022-03-17 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0005_auto_20220317_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ednDate',
            field=models.DateTimeField(default=datetime.date(2022, 3, 17)),
        ),
    ]
