# Generated by Django 2.1.5 on 2022-02-20 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0005_auto_20220220_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ltc_main.Event'),
        ),
    ]
