# Generated by Django 2.1.5 on 2022-02-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0006_auto_20220220_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='event',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='event',
            field=models.ManyToManyField(to='ltc_main.Event'),
        ),
    ]
