# Generated by Django 2.1.5 on 2022-03-17 20:40

from django.db import migrations, models
import django.utils.timezone
import eventtools.models


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0007_auto_20220317_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='event',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='ednDate',
            new_name='endDate',
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='end'),
        ),
        migrations.AddField(
            model_name='event',
            name='repeat',
            field=eventtools.models.ChoiceTextField(blank=True, choices=[('RRULE:FREQ=DAILY', 'Daily'), ('RRULE:FREQ=WEEKLY', 'Weekly'), ('RRULE:FREQ=MONTHLY', 'Monthly'), ('RRULE:FREQ=YEARLY', 'Yearly')], default='', verbose_name='repeat'),
        ),
        migrations.AddField(
            model_name='event',
            name='repeat_until',
            field=models.DateField(blank=True, null=True, verbose_name='repeat_until'),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='start'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
