# Generated by Django 2.1.5 on 2022-02-20 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0007_auto_20220220_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='event',
        ),
        migrations.RemoveField(
            model_name='student',
            name='events',
        ),
        migrations.AlterField(
            model_name='event',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ltc_main.Course'),
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
