# Generated by Django 2.1.5 on 2022-03-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0008_auto_20220317_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start', 'end')},
        ),
    ]
