# Generated by Django 2.1.5 on 2022-02-20 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0010_auto_20220220_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(default=uuid.UUID('56959a67-5dda-42e7-8beb-382f30a5d5dc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
