# Generated by Django 2.1.5 on 2022-02-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0012_auto_20220220_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
