# Generated by Django 2.1.5 on 2022-02-20 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ltc_main', '0013_auto_20220220_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='student',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='atendee',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ltc_main.Assignment'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='staff',
        ),
        migrations.AddField(
            model_name='course',
            name='staff',
            field=models.ManyToManyField(null=True, to='ltc_main.Staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
