# Generated by Django 2.1.5 on 2022-02-20 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0016_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ltc_main.TimeSlot'),
        ),
    ]
