# Generated by Django 2.1.5 on 2022-02-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0018_auto_20220220_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='staff',
        ),
        migrations.AddField(
            model_name='assignment',
            name='deadline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ltc_main.TimeSlot'),
        ),
        migrations.AddField(
            model_name='staff',
            name='assignment',
            field=models.ManyToManyField(null=True, to='ltc_main.Assignment'),
        ),
        migrations.AddField(
            model_name='staff',
            name='courses',
            field=models.ManyToManyField(null=True, to='ltc_main.Course'),
        ),
        migrations.AddField(
            model_name='staff',
            name='events',
            field=models.ManyToManyField(null=True, to='ltc_main.TimeSlot'),
        ),
        migrations.AddField(
            model_name='student',
            name='assignment',
            field=models.ManyToManyField(null=True, to='ltc_main.Assignment'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(null=True, to='ltc_main.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ltc_main.Degree'),
        ),
        migrations.AddField(
            model_name='student',
            name='events',
            field=models.ManyToManyField(null=True, to='ltc_main.TimeSlot'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='atendee',
        ),
    ]
