# Generated by Django 2.1.5 on 2022-02-21 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ltc_main', '0019_auto_20220220_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMeeting',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('creator', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='staff',
            name='assignment',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ltc_main.TimeSlot'),
        ),
        migrations.AlterField(
            model_name='student',
            name='assignment',
            field=models.ManyToManyField(blank=True, null=True, to='ltc_main.Assignment'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='ltc_main.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, to='ltc_main.TimeSlot'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
