# Generated by Django 2.1.5 on 2022-02-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0020_auto_20220221_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammeeting',
            old_name='creator',
            new_name='members',
        ),
    ]
