# Generated by Django 2.1.5 on 2022-02-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0021_auto_20220221_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammeeting',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
