# Generated by Django 2.1.5 on 2022-02-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0023_auto_20220222_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='events',
            new_name='timeSlots',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='events',
            new_name='timeSlots',
        ),
        migrations.AlterField(
            model_name='teammeeting',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
