# Generated by Django 2.1.5 on 2022-02-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltc_main', '0024_auto_20220222_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammeeting',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammeeting',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
